name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set properties
        run: echo spring.datasource.url=${{ secrets.DB_URL }} &&
        echo spring.datasource.username=${{ secrets.DB_USERNAME }} &&
        echo spring.datasource.password=${{ secrets.DB_PASSWORD }}> ./src/main/resources/application.properties
      - name: Grant execute permission for mvnw
        run: chmod +x mvnw
      - name: Build with Maven
        run: ./mvnw clean && ./mvnw package

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag iamnzrv/dimesh-api
      - name: Push the Docker image
        run: docker login --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} && docker image push iamnzrv/dimesh-api